Adding some notes to the readme
scalawag/jibe pull request #6
Opened 2016-09-28 20:36 UTC by dwcramer

@justinp

2016-09-28 20:49 UTC, ecassady approved these changes
+1

2016-09-28 20:53 UTC, justinp requested changes

2016-09-28 20:53 UTC, justinp commented on README.md
> +5. `open open results/latest/html/index.html`
open open

2016-09-29 00:07 UTC, justinp commented on README.md
> +4. `sbt run`
After merging @ecassady's most recent PR, this now needs to be `sbt core/run`.

2016-09-29 02:02 UTC, justinp approved these changes

2016-09-29 02:03 UTC, merged